### PR TITLE
Updates with moshi kotlin, updated kotlinx serialization, updated dependencies

### PR DESCRIPTION
**Pull request by ZacSweers**
New results:

```
Benchmark                                           Mode  Cnt     Score    Error  Units
SpeedTest.gson_autovalue_buffer_fromJson           thrpt  200  1305.751 ±  3.250  ops/s
SpeedTest.gson_autovalue_buffer_toJson             thrpt  200   636.358 ±  6.160  ops/s
SpeedTest.gson_autovalue_string_fromJson           thrpt  200  1435.158 ± 18.064  ops/s
SpeedTest.gson_autovalue_string_toJson             thrpt  200  1197.856 ±  2.830  ops/s
SpeedTest.gson_reflective_string_fromJson          thrpt  200  1385.616 ± 14.821  ops/s
SpeedTest.gson_reflective_string_toJson            thrpt  200   957.015 ±  4.439  ops/s
SpeedTest.kryo_fromBytes                           thrpt  200  1315.361 ±  3.594  ops/s
SpeedTest.kryo_toBytes                             thrpt  200   940.597 ±  2.033  ops/s
SpeedTest.kserializer_string_fromJson              thrpt  200  1107.929 ± 51.456  ops/s
SpeedTest.kserializer_string_toJson                thrpt  200  1175.760 ± 17.874  ops/s
SpeedTest.moshi_autovalue_buffer_fromJson          thrpt  200  1007.122 ±  3.232  ops/s
SpeedTest.moshi_autovalue_buffer_toJson            thrpt  200  1706.448 ± 17.938  ops/s
SpeedTest.moshi_autovalue_string_fromJson          thrpt  200   887.876 ±  6.539  ops/s
SpeedTest.moshi_autovalue_string_toJson            thrpt  200  1478.233 ±  2.913  ops/s
SpeedTest.moshi_kotlin_codegen_buffer_fromJson     thrpt  200   991.785 ±  5.820  ops/s
SpeedTest.moshi_kotlin_codegen_buffer_toJson       thrpt  200  1651.748 ± 18.600  ops/s
SpeedTest.moshi_kotlin_codegen_string_fromJson     thrpt  200   869.635 ±  6.311  ops/s
SpeedTest.moshi_kotlin_codegen_string_toJson       thrpt  200  1460.091 ±  3.726  ops/s
SpeedTest.moshi_kotlin_reflective_buffer_fromJson  thrpt  200   889.625 ±  2.226  ops/s
SpeedTest.moshi_kotlin_reflective_buffer_toJson    thrpt  200  1318.989 ± 16.083  ops/s
SpeedTest.moshi_kotlin_reflective_string_fromJson  thrpt  200   785.574 ±  5.834  ops/s
SpeedTest.moshi_kotlin_reflective_string_toJson    thrpt  200  1207.557 ±  8.226  ops/s
SpeedTest.moshi_reflective_string_fromJson         thrpt  200   854.247 ±  6.300  ops/s
SpeedTest.moshi_reflective_string_toJson           thrpt  200  1380.440 ± 10.762  ops/s
```

Grouped by serialization type (read, write, buffered, string):

```
Benchmark                                           Mode  Cnt     Score    Error  Units

// Reading from a JSON buffered input
SpeedTest.gson_autovalue_buffer_fromJson           thrpt  200  1305.751 ±  3.250  ops/s
SpeedTest.moshi_autovalue_buffer_fromJson          thrpt  200  1007.122 ±  3.232  ops/s
SpeedTest.moshi_kotlin_codegen_buffer_fromJson     thrpt  200   991.785 ±  5.820  ops/s
SpeedTest.moshi_kotlin_reflective_buffer_fromJson  thrpt  200   889.625 ±  2.226  ops/s

// Writing JSON to a buffered output
SpeedTest.gson_autovalue_buffer_toJson             thrpt  200   636.358 ±  6.160  ops/s
SpeedTest.moshi_autovalue_buffer_toJson            thrpt  200  1706.448 ± 17.938  ops/s
SpeedTest.moshi_kotlin_codegen_buffer_toJson       thrpt  200  1651.748 ± 18.600  ops/s
SpeedTest.moshi_kotlin_reflective_buffer_toJson    thrpt  200  1318.989 ± 16.083  ops/s

// Reading from JSON String
SpeedTest.gson_autovalue_string_fromJson           thrpt  200  1435.158 ± 18.064  ops/s
SpeedTest.gson_reflective_string_fromJson          thrpt  200  1385.616 ± 14.821  ops/s
SpeedTest.kryo_fromBytes                           thrpt  200  1315.361 ±  3.594  ops/s
SpeedTest.kserializer_string_fromJson              thrpt  200  1107.929 ± 51.456  ops/s
SpeedTest.moshi_autovalue_string_fromJson          thrpt  200   887.876 ±  6.539  ops/s
SpeedTest.moshi_kotlin_codegen_string_fromJson     thrpt  200   869.635 ±  6.311  ops/s
SpeedTest.moshi_kotlin_reflective_string_fromJson  thrpt  200   785.574 ±  5.834  ops/s
SpeedTest.moshi_reflective_string_fromJson         thrpt  200   854.247 ±  6.300  ops/s

// Writing out a JSON String
SpeedTest.gson_autovalue_string_toJson             thrpt  200  1197.856 ±  2.830  ops/s
SpeedTest.gson_reflective_string_toJson            thrpt  200   957.015 ±  4.439  ops/s
SpeedTest.kryo_toBytes                             thrpt  200   940.597 ±  2.033  ops/s
SpeedTest.kserializer_string_toJson                thrpt  200  1175.760 ± 17.874  ops/s
SpeedTest.moshi_autovalue_string_toJson            thrpt  200  1478.233 ±  2.913  ops/s
SpeedTest.moshi_kotlin_codegen_string_toJson       thrpt  200  1460.091 ±  3.726  ops/s
SpeedTest.moshi_kotlin_reflective_string_toJson    thrpt  200  1207.557 ±  8.226  ops/s
SpeedTest.moshi_reflective_string_toJson           thrpt  200  1380.440 ± 10.762  ops/s
```

Grouped by library (interesting to see how reflection vs custom adapters affects perf within a library):

```
Benchmark                                           Mode  Cnt     Score    Error  Units

// Gson
SpeedTest.gson_autovalue_buffer_fromJson           thrpt  200  1305.751 ±  3.250  ops/s
SpeedTest.gson_autovalue_buffer_toJson             thrpt  200   636.358 ±  6.160  ops/s
SpeedTest.gson_autovalue_string_fromJson           thrpt  200  1435.158 ± 18.064  ops/s
SpeedTest.gson_reflective_string_fromJson          thrpt  200  1385.616 ± 14.821  ops/s
SpeedTest.gson_autovalue_string_toJson             thrpt  200  1197.856 ±  2.830  ops/s
SpeedTest.gson_reflective_string_toJson            thrpt  200   957.015 ±  4.439  ops/s

// Moshi
SpeedTest.moshi_autovalue_buffer_fromJson          thrpt  200  1007.122 ±  3.232  ops/s
SpeedTest.moshi_autovalue_buffer_toJson            thrpt  200  1706.448 ± 17.938  ops/s
SpeedTest.moshi_autovalue_string_fromJson          thrpt  200   887.876 ±  6.539  ops/s
SpeedTest.moshi_reflective_string_fromJson         thrpt  200   854.247 ±  6.300  ops/s
SpeedTest.moshi_autovalue_string_toJson            thrpt  200  1478.233 ±  2.913  ops/s
SpeedTest.moshi_reflective_string_toJson           thrpt  200  1380.440 ± 10.762  ops/s

// Moshi Kotlin
SpeedTest.moshi_kotlin_codegen_buffer_fromJson     thrpt  200   991.785 ±  5.820  ops/s
SpeedTest.moshi_kotlin_reflective_buffer_fromJson  thrpt  200   889.625 ±  2.226  ops/s
SpeedTest.moshi_kotlin_codegen_buffer_toJson       thrpt  200  1651.748 ± 18.600  ops/s
SpeedTest.moshi_kotlin_reflective_buffer_toJson    thrpt  200  1318.989 ± 16.083  ops/s
SpeedTest.moshi_kotlin_codegen_string_fromJson     thrpt  200   869.635 ±  6.311  ops/s
SpeedTest.moshi_kotlin_reflective_string_fromJson  thrpt  200   785.574 ±  5.834  ops/s
SpeedTest.moshi_kotlin_codegen_string_toJson       thrpt  200  1460.091 ±  3.726  ops/s
SpeedTest.moshi_kotlin_reflective_string_toJson    thrpt  200  1207.557 ±  8.226  ops/s

// Misc
SpeedTest.kryo_fromBytes                           thrpt  200  1315.361 ±  3.594  ops/s
SpeedTest.kserializer_string_fromJson              thrpt  200  1107.929 ± 51.456  ops/s
SpeedTest.kryo_toBytes                             thrpt  200   940.597 ±  2.033  ops/s
SpeedTest.kserializer_string_toJson                thrpt  200  1175.760 ± 17.874  ops/s
```

### CODE REVIEW

**Comment by ZacSweers** [comment]
CC @swankjesse @riclage @elizarov @sandwwraith 

Also if anyone tries to run this locally, it takes just under 3 hours.

**Comment by ZacSweers** [comment]
Updated with minified JSON.

```
# Run complete. Total time: 03:37:38

Benchmark                                                    Mode  Cnt     Score    Error  Units
SpeedTest.gson_autovalue_buffer_fromJson                    thrpt  200  1305.687 ±  4.756  ops/s
SpeedTest.gson_autovalue_buffer_fromJson_minified           thrpt  200  1500.076 ±  3.238  ops/s
SpeedTest.gson_autovalue_buffer_toJson                      thrpt  200   616.999 ±  1.365  ops/s
SpeedTest.gson_autovalue_string_fromJson                    thrpt  200  1501.642 ± 16.501  ops/s
SpeedTest.gson_autovalue_string_fromJson_minified           thrpt  200  1610.007 ± 23.511  ops/s
SpeedTest.gson_autovalue_string_toJson                      thrpt  200  1221.374 ±  2.972  ops/s
SpeedTest.gson_reflective_string_fromJson                   thrpt  200  1429.620 ±  8.491  ops/s
SpeedTest.gson_reflective_string_toJson                     thrpt  200   977.967 ±  4.039  ops/s
SpeedTest.kryo_fromBytes                                    thrpt  200  1337.743 ±  3.532  ops/s
SpeedTest.kryo_toBytes                                      thrpt  200   951.468 ±  1.999  ops/s
SpeedTest.kserializer_string_fromJson                       thrpt  200   933.622 ± 58.509  ops/s
SpeedTest.kserializer_string_fromJson_minified              thrpt  200  1116.711 ± 68.464  ops/s
SpeedTest.kserializer_string_toJson                         thrpt  200  1197.405 ± 13.311  ops/s
SpeedTest.moshi_autovalue_buffer_fromJson                   thrpt  200  1019.747 ±  4.865  ops/s
SpeedTest.moshi_autovalue_buffer_fromJson_minified          thrpt  200  1374.263 ±  4.125  ops/s
SpeedTest.moshi_autovalue_buffer_toJson                     thrpt  200  1659.574 ± 15.520  ops/s
SpeedTest.moshi_autovalue_string_fromJson                   thrpt  200   884.915 ±  8.067  ops/s
SpeedTest.moshi_autovalue_string_fromJson_minified          thrpt  200  1187.466 ±  8.148  ops/s
SpeedTest.moshi_autovalue_string_toJson                     thrpt  200  1486.164 ±  7.188  ops/s
SpeedTest.moshi_kotlin_codegen_buffer_fromJson              thrpt  200  1008.205 ±  5.708  ops/s
SpeedTest.moshi_kotlin_codegen_buffer_fromJson_minified     thrpt  200  1345.220 ±  3.571  ops/s
SpeedTest.moshi_kotlin_codegen_buffer_toJson                thrpt  200  1699.049 ±  9.304  ops/s
SpeedTest.moshi_kotlin_codegen_string_fromJson              thrpt  200   894.285 ±  4.104  ops/s
SpeedTest.moshi_kotlin_codegen_string_fromJson_minified     thrpt  200  1198.403 ±  5.119  ops/s
SpeedTest.moshi_kotlin_codegen_string_toJson                thrpt  200  1484.823 ±  3.913  ops/s
SpeedTest.moshi_kotlin_reflective_buffer_fromJson           thrpt  200   891.004 ±  3.154  ops/s
SpeedTest.moshi_kotlin_reflective_buffer_fromJson_minified  thrpt  200  1134.176 ±  3.934  ops/s
SpeedTest.moshi_kotlin_reflective_buffer_toJson             thrpt  200  1335.505 ± 18.700  ops/s
SpeedTest.moshi_kotlin_reflective_string_fromJson           thrpt  200   784.143 ±  5.367  ops/s
SpeedTest.moshi_kotlin_reflective_string_toJson             thrpt  200  1206.002 ±  5.596  ops/s
SpeedTest.moshi_reflective_string_fromJson                  thrpt  200   853.909 ±  4.197  ops/s
SpeedTest.moshi_reflective_string_toJson                    thrpt  200  1383.914 ±  9.629  ops/s
```

**Comment by allidoiswarren** [comment]
Any plans to add Gson reflective serialization for Kotlin data classes? Would be nice to put that side-by-side with Kotlin Codegen adapters since that's an upgrade path I've seen in popular apps.

**Comment by riclage** [comment]
@allidoiswarren I was curious so I added data class tests here: #5

**Pull request merged**
