### PR TITLE
Convert models to Kotlin and add kotlix.serialization benchmark

### PR DESCRIPTION
**Pull request by riclage**
We add the benchmark for [kotlix.serialization](https://github.com/Kotlin/kotlinx.serialization), the Kotlin cross-platform / multi-format serialization.

In order to do so, we needed to convert the models to Kotlin and annotate the model classes with `@Serializable` and fields with custom serial names with `@SerialName`.

Here are the results running `./gradlew jmh` for the `largesample.json` file on a 13" Macbook Pro 2.7 GHz Intel Core i7, 16 GB 1600 MHz DDR3 machine (higher scores are better):

```
Benchmark                             Mode  Cnt     Score    Error  Units
SpeedTest.gson_reflective_fromJson   thrpt  200   637.594 ± 11.412  ops/s
SpeedTest.gson_reflective_toJson     thrpt  200   753.715 ± 18.660  ops/s

SpeedTest.gson_streaming_fromJson    thrpt  200   674.394 ±  7.945  ops/s
SpeedTest.gson_streaming_toJson      thrpt  200  1039.328 ± 20.608  ops/s

SpeedTest.kserializer_fromJson       thrpt  200   384.018 ±  3.459  ops/s
SpeedTest.kserializer_toJson         thrpt  200   403.390 ±  1.846  ops/s

SpeedTest.moshi_reflective_fromJson  thrpt  200   771.601 ±  8.017  ops/s
SpeedTest.moshi_reflective_toJson    thrpt  200  1202.966 ±  6.690  ops/s

SpeedTest.moshi_streaming_fromJson   thrpt  200   815.384 ±  3.021  ops/s
SpeedTest.moshi_streaming_toJson     thrpt  200  1284.325 ±  6.018  ops/s
```

I'm not sure yet why the performance is this much slower with kotlix.serialization. I would like to investigate this further but not sure where to start yet.

### CODE REVIEW

**Comment by ZacSweers** [comment]
Neat! Mind rebasing? Forgot I had a stale unmerged PR with some cleanups

**Comment by riclage** [comment]
Done. :)

**Comment by ZacSweers** [comment]
Cool. The setup looks good to me. Mind if we leave this as a PR for now and see what they say in https://github.com/Kotlin/kotlinx.serialization/issues/89? I suspect they might ask you to try a couple different things or tweak some parameters, so might be easier for you to iterate on it in a PR

**Comment by elizarov** [comment]
Thanks for the branch. I've used it to improve `kotlinx.coroutines` JSON serialization performance, but I've made a number of tweaks to be build. I'll enumerate them here:

1. Use Gradle 4.3 

```
task wrapper(type: Wrapper) {
    gradleVersion = '4.3' 
    distributionUrl = "https://services.gradle.org/distributions/gradle-$gradleVersion-all.zip"
}
```

(and update the wrapper)

2. Use the latest version of Gradle JMH plugin: 

```
buildscript {
    depdendencies {
        classpath "me.champeau.gradle:jmh-gradle-plugin:0.4.5"
    }
}
```
3. Use the latest kotlin, serialization and JMH versions:

```
buildscript {
    ext.kotlin_version = '1.2.30'
    ext.serialization_version = '0.4.2'
    ext.jmh_version = '1.20'
}

jmh {
    jmhVersion = jmh_version
}
```

4. Add shadow plugin and explicit compile dependencies on JMH core so that `./gradlew jmhJar` actually builds a self-contained uber-jar that can be used with `java -jar` to run benchmarks:

```
buildscript {
    depdendencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:2.0.2"
    }
}

apply plugin: "com.github.johnrengelman.shadow"

dependencies {
    compile "org.openjdk.jmh:jmh-core:$jmh_version"
    compile 'com.google.guava:guava:22.0' // THIS HAS TO BE COMPILE DEPENDENCY !!!
}
```

**Comment by ZacSweers** [comment]
FYI Moshi 1.6 is out now with native kotlin codegen support. I can take a crack at updating the code here to compare that too and also pull in Roman's changes in his tests

**Pull request merged**
